const adminTypes = {
  LAY_DANH_SACH_NGUOI_DUNG: "LAY_DANH_SACH_NGUOI_DUNG",

  LAY_DS_NGUOI_DUNG_RENDER: "LAY_DS_NGUOI_DUNG_RENDER",

  XOA_NGUOI_DUNG: "XOA_NGUOI_DUNG",

  SEARCH_USER: "SEARCH_USER",
  LAY_DS_KH_CHUA_XET_DUYET: "LAY_DS_KH_CHUA_XET_DUYET",
  LAY_DS_KH_DA_XET_DUYET: "LAY_DS_KH_DA_XET_DUYET",
  LAY_DS_KH_CHO_XET_DUYET: "LAY_DS_KH_CHO_XET_DUYET",
  LAY_DS_HV_CHO_XET_DUYET: "LAY_DS_HV_CHO_XET_DUYET",
  LAY_DS_HV_KHOA_HOC: "LAY_DS_HV_KHOA_HOC",
};

export default adminTypes;
