const courseTypes = {
  LAY_DANH_SACH: "LAY_DANH_SACH",
  LAY_CHI_TIET_KHOA_HOC: "LAY_CHI_TIET_KHOA_HOC",
  LAY_KHOA_HOC_THEO_SEARCH: "LAY_KHOA_HOC_THEO_SEARCH",
  LAY_KHOA_HOC_THEO_NGUOI_DUNG: "LAY_KHOA_HOC_THEO_NGUOI_DUNG",
  
};
export default courseTypes;
